# Generated by Django 4.1.4 on 2023-08-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_movie_rating_remove_movie_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movieId',
        ),
    ]
