# Generated by Django 4.1.4 on 2023-08-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_movie_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
