# Generated by Django 4.1.4 on 2023-08-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
